import fs from 'fs'

export const useJavascriptTemplate = (data: any, filePath: string) => {
   // prettier-ignore
   fs.writeFileSync(
      filePath,
`/* This file has been generated by a Lotion configuration script. */

const DATA = ${JSON.stringify(data, null, 2)}
export default DATA`
   )
}
